FROM golang:1.15-alpine

RUN apk add --no-cache git
WORKDIR /tmp/subscription-service

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -o /usr/bin/subscription-service .

LABEL maintainer="Michel Bongard"

ENTRYPOINT [ "/usr/bin/subscription-service" ]
