apiVersion: v1
kind: Service
metadata:
  labels:
    app: subscription-service-secret
  name: subscription-service-secret
spec:
  ports:
  - name: 9000-8080
    port: 8080
    protocol: TCP
    targetPort: 9000
  selector:
    app: subscription-service-secret
  type: ClusterIP