name: build_and_push

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            insost/jagw-subscription-service:latest
            insost/jagw-subscription-service:${{ steps.get_release.outputs.tag_name }}
            ghcr.io/jalapeno-api-gateway/jagw-subscription-service:latest
            ghcr.io/jalapeno-api-gateway/jagw-subscription-service:${{ steps.get_release.outputs.tag_name }}
